### ISSUE TITLE
Cannot find module '../utils/Utils' or its corresponding type declarations.

### ISSUE THREAD

**Issue by fregante** [primefaces/primereact#2462]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

If you haven't caught it until now, it means it Codesandbox can't replicate it.

**Current behavior**

```

node_modules/primereact/treenode/treenode.d.ts:1:24 - error TS2307: Cannot find module '../utils/Utils' or its corresponding type declarations.

1 import {IconType} from "../utils/Utils";
                         ~~~~~~~~~~~~~~~

Found 1 error.
```

**Expected behavior**

No error

**Minimal reproduction of the problem with instructions**

On a case-sensitive FS

```
npm install primereact
npm install @types/react
npm install typescript
echo 'import { TreeTable } from "primereact/treetable";' > index.ts
echo '{"files": ["index.ts"], "compilerOptions": {"lib": ["ES2019"]}}' > tsconfig.json
npx tsc
```

**GitHub Actions** 

You can test this on GHA since it's case-sensitive. The output can currently be seen at https://github.com/fregante/sandbox/runs/4299166102?check_suite_focus=true

```yml
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install primereact
      - run: npm install @types/react
      - run: npm install typescript
      - run: echo 'import { TreeTable } from "primereact/treetable";' > index.ts
      - run: |
          echo '{"files": ["index.ts"], "compilerOptions": {"lib": ["ES2019"]}}' > tsconfig.json
      - run: npx tsc
```

**Please tell us about your environment:**

GitHub Actions, `runs-on: ubuntu-latest`

* **React version:** 17

* **PrimeReact version:** starting with v7.0.0

* **Browser:** N/A
 
* **Language:** TypeScript 4.5
