### ISSUE TITLE
Not diplay sort icons if sorting is not applied

### ISSUE THREAD

**Issue by augustosnk12** [primefaces/primereact#2477]
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

First of all, I would like to thank all you supporting that lib. It literally saves my life 😁.
So, I'm requesting here a little (or not) feature in [DataTable](https://primefaces.org/primereact/showcase/#/datatable) component, specifically in the **sort** thing. I would like some props to display the sort icon ONLY when I apply the sorting. Currently the sort icons are displayed everytime in every column.

**Comment by melloware** [comment]
You don't need new code for this. Just add this CSS Style to your `.css` file for your app and it will hide them and only display them when the column is sorted.

```css
body th.p-sortable-column:not(.p-highlight) > .p-column-header-content .p-sortable-column-icon {
  display: none;
}
```
