### ISSUE TITLE
Datatable:  Responsive broken in 7.2.0

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#2594]
If you go to the Showcase Responsive demo in 7.1.0 it works properly when shrinking your browser. However in 7.2 all of the Responsive UI features seem broken.

https://www.primefaces.org/primereact-v7/#/datatable/responsive

You can see its not stacking and the whole site seems not to be respecting the media queries.  This is happening in my local app too.

**7.1.0 Correct**
![image](https://user-images.githubusercontent.com/4399574/150422454-132e4cea-c774-4dc2-880e-1b0015bf7f6e.png)

**7.2.0 INCORRECT**
![image](https://user-images.githubusercontent.com/4399574/150422576-c1d619d3-0fe5-46f7-b618-fe704e072007.png)

**Comment by melloware** [comment]
It looks like the dynamic inline styles are not being created...

```css
@media screen and (max-width: 960px)
<style>
.p-datatable[pr_id_2] .p-datatable-tbody > tr > td {
    display: flex;
    width: 100% !important;
    align-items: center;
    justify-content: space-between;
}
```
