### ISSUE TITLE
Bug on Dark Themes related with fixed columns

### ISSUE THREAD

**Issue by wolnynick** [primefaces/primereact#2630]
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57

**Current behavior**
On Vela-Blue theme there is a error with fixed columns, because background color on stripped rows and also on hover have opacity and because of it we can see values from not fixed columns under fixed columns after scroll

Before scroll:

![image](https://user-images.githubusercontent.com/40297940/152507305-74082fe6-72eb-4929-83d7-3f9252e5c146.png)

After scroll:

![image](https://user-images.githubusercontent.com/40297940/152507593-c987a68f-d72e-4484-9ced-ebfd6ec7853f.png)

Classes responsible for this bug:

```css
.p-datatable.p-datatable-striped .p-datatable-tbody > tr.p-row-odd {
    background: rgba(255, 255, 255, 0.01);
}
```

```css
.p-datatable.p-datatable-hoverable-rows .p-datatable-tbody > tr:not(.p-highlight):not(.p-datatable-emptymessage):hover {
    background: rgba(255, 255, 255, 0.03);
    color: rgba(255, 255, 255, 0.87);
}
```

**React version:**
17.0.2

**PrimeReact version:**
7.2.0

**Comment by melloware** [comment]
I can't imagine its just vela-blue i would assume all the themes have this problem?

**Comment by wolnynick** [comment]
I don't know, I use only **Saga-Blue** and **Vela-Blue** and on **Saga-Blue** I don't have any problems because in this theme there is no opacity in these classes:

```css
.p-datatable.p-datatable-striped .p-datatable-tbody > tr.p-row-odd {
    background: #fcfcfc;
}
```

```css
.p-datatable.p-datatable-hoverable-rows .p-datatable-tbody > tr:not(.p-highlight):not(.p-datatable-emptymessage):hover {
    background: #e9ecef;
    color: #495057;
}
```
