### ISSUE TITLE
Component:Toast

### ISSUE THREAD

**Issue by andreiGadjylaJS** [primefaces/primereact#2926]
### Describe the bug

If the content of the error is one large line, the text will go outside the component
![image](https://user-images.githubusercontent.com/63897995/170208939-94f9d3cc-85d6-45cb-9e05-7d8807b41edc.png)

### Reproducer

https://codesandbox.io/s/gallant-banzai-soo2gq

### PrimeReact version

8.1.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 101.0.4951.67

### Expected behavior

Text remained within the error output window

**Comment by melloware** [comment]
Add this CSS to your CSS that loads after PrimeReact.

```css
.p-toast .p-toast-message .p-toast-message-content .p-toast-detail {
    overflow-wrap: anywhere;
}
```
