### ISSUE TITLE
Changed colors in toast component

### ISSUE THREAD

**Issue by LeonardoYoel** [primefaces/primereact#3103]
I am using the theme that primereact provides from tailwind-ligth, but the border of the toast should have the color of the severity, and it stays permanently gray. However with other themes it does not happen.
That's right?![IMG_20220724_112305.jpg](https://user-images.githubusercontent.com/46235379/180654115-5f1546e7-c089-40b5-be14-4a07aaddfbc5.jpg)

**Comment by melloware** [comment]
It looks like on Tailwind Light this was intentional to have no `border`
![image](https://user-images.githubusercontent.com/4399574/180773819-dae2665f-f3dc-41d4-9420-8275dd3a3c58.png)

If you want a border just add this to your App.css stylessheet
```css
.p-toast .p-toast-message.p-toast-message-info {
   border: solid #2563EB;
}
.p-toast .p-toast-message.p-toast-message-success {
   border: solid #059669;
}
.p-toast .p-toast-message.p-toast-message-warn {
   border: solid #D97706;
}
.p-toast .p-toast-message.p-toast-message-error {
   border: solid #DC2626;
}
```
