### ISSUE TITLE
AutoComplete: Allow left and right icon like InputText

### ISSUE THREAD

**Issue by melloware** [primefaces/primereact#3475]
### Describe the feature you would like to see added

![image](https://user-images.githubusercontent.com/4399574/195590604-95dfbaf9-0b9c-4082-9492-88480d761985.png)

Similar to InputText the theme.css needs to add:

```css
.p-input-icon-left > .p-autocomplete > .p-autocomplete-input {
    padding-left: 2.5rem;
  }


.p-input-icon-right > .p-autocomplete > .p-autocomplete-input {
    padding-right: 2.5rem;
  }
```
