### ISSUE TITLE
MenuBar: Add prop to disable responsive

### ISSUE THREAD

**Issue by bhkangw** [primefaces/primereact#3480]
### Describe the feature you would like to see added

The MenuBar by default collapses into a hamburger menu when the screen width is 960px or less. However, sometimes you don't want to allow the menu to collapse at all.

Here is a [request from PrimeVue](https://forum.primefaces.org/viewtopic.php?t=72635) asking for the same thing that was left unanswered.

### Describe the solution you'd like

A prop such as `responsive={false}` that prevents the MenuBar from automatically resizing OR a prop that let's you set the width when it will collapse.

**Comment by melloware** [comment]
This is actually set in the `theme.css` and not the component itself.  If you want to turn it off just add this CSS to your application.

```css
@media screen and (max-width: 960px) {
     .p-menubar .p-menubar-button {
         display: none;
    }
     .p-menubar {
         position: inherit;
    }
     .p-menubar .p-menubar-root-list {
         display: flex;
         align-items: center;
         position: unset;
         padding: unset;
         background: inherit;
         border: unset;
         box-shadow: unset;
         width: unset;
    }
}
```
