### ISSUE TITLE
DataTable: Frozen columns have transparent background on the Arya theme

### ISSUE THREAD

**Issue by rschyboll** [primefaces/primereact#3700]
### Describe the bug

The DataTable component, has an incorrect style on the Arya theme, when using it with frozen columns and selectable rows. 
When freezing a column, and scrolling the datatable, so that some column is under the frozen one, the background of the frozen column will become partially transparent on selection or mouse hover, showing the data of the column under it.

It also seems, that the outline is also broken, if it's neccesary i can create a new issue, but this seems to be related, so i'm currently putting it only here.

### Reproducer

https://codesandbox.io/s/silly-minsky-0oe4go?file=/src/demo/DataTableScrollDemo.js

### PrimeReact version

8.7.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome 107

### Steps to reproduce the behavior

1. Create a scrollable datatable with selectable rows and frozen columns
2. Scroll the datatable so that some column are under the frozen ones
3. Select a row or hover over it
4. The data of the column under the frozen one will be visible

### Expected behavior

The frozen column should not be transparent, when selected or hovered. 

I fixed it by setting the the background color myself, with the following selector:
```scss
.p-highlight.p-selectable-row {
  .p-frozen-column {
    background-color: var(--table-row-select-color);
  }
}
```

**Comment by melloware** [comment]
Is this a duplicate of this? https://github.com/primefaces/primereact/issues/3230

**Comment by melloware** [comment]
Actually I think this is the more accurate selector?  You only want this when you frozen is highlighted.

```css
.p-datatable .p-datatable-tbody > tr.p-highlight > td.p-frozen-column {
  background-color: var(--table-row-select-color);
}
```
