### ISSUE TITLE
Button: No margin/padding between button text and loading spinner

### ISSUE THREAD

**Issue by ewenjo** [primefaces/primereact#4320]
### Describe the bug

Buttons without an icon have no margin between the loading spinner and the button text. Although, I'm not entirely sure if this is a bug or intended behavior.

![image](https://user-images.githubusercontent.com/4399574/235447151-67816cbe-cf3f-4b6f-946f-43ce336c30db.png)

### Reproducer

https://codesandbox.io/s/primereact-demo-forked-u2xxwe?file=/src/App.js

### PrimeReact version

9.3.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

Create a button without setting an icon, set the loading state.

### Expected behavior

I would expect there to be some padding, similar to the padding there is when a button has an icon.

**Comment by melloware** [comment]
The issue is the theme is doing this on purpose for some reason:

```css
.p-button.p-button-loading-label-only .p-button-loading-icon {
  margin: 0;
}
```

Workaround is to add this CSS.

```css
.p-button.p-button-loading-label-only .p-button-loading-icon {
  margin: 0;
  margin-right: 0.5rem;
}
```
