### ISSUE TITLE
SlideMenu: Seperator missing

### ISSUE THREAD

**Issue by Ocean15** [primefaces/primereact#4528]
### Describe the bug

As stated in the documentation example for SlideMenu you can use a seperator item. But the seperator item isn't rendered at all.

### Reproducer

https://codesandbox.io/s/dzk8kb

### PrimeReact version

9.5.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Add seperator item to SlideMenu
2. Render SlideMenu
3. No seperator

### Expected behavior

SlideMenu with seperator

**Comment by melloware** [comment]
Great catch.  Needs to be fixed in the theme but if you need to fix it right now just add this CSS

```css
body .p-slidemenu .p-menu-separator {
  border-top: 1px solid var(--surface-border);
}
```
