### ISSUE TITLE
DataTable: VirtualScrollOption

### ISSUE THREAD

**Issue by Kirito078** [primefaces/primereact#4775]
### Describe the bug

I have a problem with the Virtualscroller in DataTable component (itemSize:46). What's happening is that the first rows work as expected with the CSS, but the subsequent ones don't have cell borders applied, specifically those that go beyond the configured 46 rows. All rows have the same CSS styles and I picked the PrimeReact class.

That's my CSS, and in the DataTable, it doesnt work properly when I reach the 46 row. It's like it's not in the style, but it really is since I find it in the inspect element.

```css
.p-datatable-table .p-datatable-tbody > tr{
  border-width: 2px ;
  
}

.p-datatable-table .p-datatable-tbody > tr > td, .p-datatable .p-datatable-thead > tr > th,
.p-virtualscroller-content > tr > td{
  border-width: 0 1.2px 0 1.2px ;
  border-color: #DCDCDC ;
  
}
```

### PrimeReact version

9.6.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)
