### ISSUE TITLE
DataTable: props stripedRows not working

### ISSUE THREAD

**Issue by nazmulislam** [primefaces/primereact#4910]
### Describe the bug

The stripedRows is not working see the docs demo for example

### PrimeReact version

9.6.2

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

**Comment by melloware** [comment]
Hmm can you check my reproducer it seems to be working for me: https://stackblitz.com/edit/react-fjpupz

**Comment by nazmulislam** [comment]
So, i can confirm the striped rows are working, however, the striped background color is light and almost white.
I have attached a screenshot.
 it would be useful to add prop for changing the background colour
![Screenshot 2023-09-11 at 19 11 31](https://github.com/primefaces/primereact/assets/3844908/aa29a9ec-7661-4d39-8f05-c6b0a2a3dd57)

**Comment by melloware** [comment]
Just use CSS:

```css
.p-datatable.p-datatable-striped .p-datatable-tbody > tr.p-row-odd {
    background-color: darkgrey;
    color: white;
}
```


![image](https://github.com/primefaces/primereact/assets/4399574/27fb86ca-ae70-4eab-be57-aaa93fad45a5)
