### ISSUE TITLE
how to set row height for treetable

### ISSUE THREAD

**Issue by CharellKing** [primefaces/primereact#4943]
### Describe the feature you would like to see added

`.p-treetable .p-treetable-tbody > tr {
  height: 50px; /* Set the desired row height */
}`

`
<TreeTable
  rowClassName={(node) => {
      return { 'h-10': true }; 
  }}  
>

</TreeTable>
`
all the methods are not worked.

**Comment by melloware** [comment]
Working Sandbox: https://stackblitz.com/edit/react-w3vhmo?file=src%2FApp.js,src%2Findex.css

```css
.p-treetable .p-treetable-tbody > tr {
  height: 100px;
}
```

CSS works fine for me.
