### ISSUE TITLE
PrimeReactProvider: Panels closing on scroll even with hideOverlaysOnDocumentScrolling: false

### ISSUE THREAD

**Issue by MBR-0001** [primefaces/primereact#5332]
### Describe the bug

Setting `hideOverlaysOnDocumentScrolling: false` in PrimeReactProvider does not keep the overlays open when scrolling, check reproducer

### Reproducer

https://codesandbox.io/s/primereact-forked-pdt7mn?file=/src/index.js:1025-1063

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Steps to reproduce the behavior

1. Open a dropdown
2. Scroll
3. Observe that the dropdown panel closed

### Expected behavior

Dropdown panel remains open

**Comment by melloware** [comment]
Issue was caused by this fix: https://github.com/primefaces/primereact/issues/4819

**Comment by MBR-0001** [comment]
Doesn't seem to be fixed, still occurring in 10.2.1 https://codesandbox.io/p/sandbox/primereact-forked-65n5gl

**Comment by melloware** [comment]
OK in the showcase this is working fine. but I can see your example is not trying to figure out why.

**Comment by melloware** [comment]
@MBR-0001 i found the difference. It is because its attaching to Window and not body.

I added this CSS

```css
body {
  margin: 0px;
  min-height: 100%;
  overflow-x: hidden;
  overflow-y: auto;
  background-color: var(--surface-ground);
  font-weight: normal;
  color: var(--text-color);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

And now it works fine.

https://codesandbox.io/p/sandbox/primereact-forked-75lqfn
