### ISSUE TITLE
Dock: Sample code missing DockDemo.css

### ISSUE THREAD

**Issue by 13RTK** [primefaces/primereact#5882]
### Describe the bug

In the doc of [Dock](https://primereact.org/dock/) component, the sample code missing the css file, even error at the [stackblitz](https://stackblitz.com/~/edit/tclas5)

![image](https://github.com/primefaces/primereact/assets/63441399/09f61ce5-6d5d-45dc-a613-733ec704435a)
![image](https://github.com/primefaces/primereact/assets/63441399/c41d4782-1eb5-4b33-ac10-2fc872277ba0)

### PrimeReact version

10.4.0

### React version

18.x

### Language

ES6

### Build / Runtime

Vite

**Comment by melloware** [comment]
Good catch thanks for the report!

**Comment by melloware** [comment]
If you need the CSS its this:

```css
/* DockDemo.css */
.dock-demo .dock-window {
    width: 100%;
    height: 450px;
    position: relative;
    background-image: url('https://primefaces.org/cdn/primereact/images/dock/window.jpg');
    background-repeat: no-repeat;
    background-size: cover;
}
.dock-demo .p-dock {
    z-index: 1000;
}  
```
