### ISSUE TITLE
Stepper: Add label placement config in StepperPanel 

### ISSUE THREAD

**Issue by TikouWeb** [primefaces/primereact#7025]
Similar to button iconPos it would be cool to have this option in stepper panel. 
Libraries like MUI and Ant have this option : [MUI](https://mui.com/material-ui/react-stepper/#alternative-label)  -  [ANT](https://ant.design/components/steps#steps-demo-label-placement)

```jsx
<Stepper >
    <StepperPanel header="Header I" headerPos="right | left | bottom">
        <div className="flex flex-column h-12rem">
            <div>Content I</div>
        </div>
    </StepperPanel>
</ Stepper>
```

**Comment by melloware** [comment]
Just call it `position` similar to Toast: https://primereact.org/toast/#position

**Comment by TikouWeb** [comment]
@melloware 

i think it is more reliable to add the prop at the stepper root component the position of headers should be the same for all steps. so small update for the proposition above: 

```jsx
<Stepper headerPosition="top | right | bottom | left">
    <StepperPanel header="Header I">
        <div className="flex flex-column h-12rem">
            <div>Content I</div>
        </div>
    </StepperPanel>
     <StepperPanel header="Header II">
        <div className="flex flex-column h-12rem">
            <div>Content I</div>
        </div>
    </StepperPanel>
    <StepperPanel header="Header III">
        <div className="flex flex-column h-12rem">
            <div>Content I</div>
        </div>
    </StepperPanel>
</ Stepper>
```

Here is a first workaround

<img width="986" alt="Screenshot 2024-08-12 at 01 05 19" src="https://github.com/user-attachments/assets/364bc930-a05f-47cd-bfba-761040d46a62">

**Comment by melloware** [comment]
Ok then just "position" then.

**Comment by TikouWeb** [comment]
'headerPosition' offers several advantages over just 'position':

1. It's more specific and self-explanatory.
2. It avoids confusion with the existing 'orientation' prop.
3. It clearly indicates we're positioning headers, not the entire Stepper.

a developer encountering a 'position' prop at the Stepper level might not immediately understand its specific purpose

What do you think about these points? I'm open to further discussion to find the right balance.

**Comment by melloware** [comment]
OK I am good with `headerPosition`

**Comment by TikouWeb** [comment]
Hello @melloware ,

The feature will soon be complete, including tests for this feature and existing ones. However, before finalising, I have a question about custom themes.

Currently, we have a `.p-stepper-title` witch is customised in themes:

```css
/* in the custom theme */
.p-stepper .p-stepper-header .p-stepper-action .p-stepper-title {
    margin-left: 0.5rem;
    color: #6b7280;
    font-weight: 700;
    transition: background-color 0.2s, color 0.2s, box-shadow 0.2s;
}
```
For the feature, i added new classes for different positions and they got overwritten by the theme class above 

```css
/* new feature classes */
.p-stepper-title-bottom {
    margin-top: 1rem;
}
.p-stepper-title-top {
    margin-bottom: 1rem;
}
.p-stepper-title-right {
    margin-left: 0.5rem;
}
.p-stepper-title-left {
    margin-right: 0.5rem;
}
```

I'm not sure how to update existing themes with these new classes. I imagine there's a script to run or something like that. Any idea on how to get this done ? Thanks !
