### ISSUE TITLE
@layer directive incompatibility with Safari 14 when using PrimeReact with TailwindCSS

### ISSUE THREAD

**Issue by amendezm** [primefaces/primereact#7146]
### Describe the bug

The `@layer` directive used in conjunction with PrimeReact's CSS themes and TailwindCSS causes compatibility issues in Safari 14, as Safari 14 does not support the `@layer` directive. This breaks styles for PrimeReact components when used in projects that rely on TailwindCSS and attempt to organize layers using the `@layer` directive.

### System Information

```Shell
"primereact": "10.8.2"
"tailwindcss": "3.4.10"
"react": "18.2.0"
```

### Steps to reproduce the behavior

1. Set up a project using PrimeReact and TailwindCSS.
2. Use the `@layer` directive to define custom layers for `tailwind-base`, `primereact`, `tailwind-utilities`, and `custom-styles`.
3. Open the project in Safari 14.

Example configuration:
```css
@layer tailwind-base, primereact, tailwind-utilities, custom-styles;

@import "primereact/resources/themes/lara-light-blue/theme.css" layer(primereact);

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}

@layer base {
  :root {
    --color-primary: 107deg 42% 59%;
    --color-primary-hover: 107deg 35% 52%;
    --color-secondary: 196deg 71% 46%;
    --color-secondary-hover: 196deg 64% 39%;
    --color-photo-bg-color: 107deg 42% 59%;
  }
}
```

### Expected behavior

For styles to be correctly applied or for guidance on how to maintain PrimeReact and TailwindCSS compatibility in browsers like Safari 14 that do not support @layer.
