### ISSUE TITLE
Documentation for CSS Modules: Cascaded classes

### ISSUE THREAD

**Issue by StopNGo** [primefaces/primereact#7347]
### Describe the bug

Hi!

Your current documentation states:
> Unfortunately CSS modules do not support cascaded classes to be applied to external components however attribute selectors can be used as a common workaround

And then, in the example:
```css
/* paneldemo.module.css */
.mypanel > [class~="p-panel-header"] {
    background-color: #07c4e8;
    color: #ffffff;
}
```

However, you can use the :global selector. You can check the CSS Modules documentation here: [Composition -> Exceptions](https://github.com/css-modules/css-modules/blob/master/docs/composition.md#exceptions).

So, the example above should be:
```css
/* paneldemo.module.css */
.mypanel :global(.p-panel-header) {
    background-color: #07c4e8;
    color: #ffffff;
}
```

This is an official working solution for cascading classes in CSS Modules.

I think you should review this from your side and update your documentation accordingly.

Thanks for your work!

### System Information

```Shell
Any system
```

### Steps to reproduce the behavior

On any project with CSS Modules use :global selector instead attribute selector.
